spring.application.name=jobjournalcapstone
spring.datasource.url=jdbc:postgresql://localhost:5432/job_journal
spring.datasource.username=postgres
spring.datasource.password=password

app.url=http://localhost:8080